#!/usr/bin/env python3
import re
import sys
from pathlib import Path


script = Path(sys.argv[1])
text = script.read_text(encoding="utf-8")


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    sys.exit(1)


def require(pattern: str, message: str, flags: int = 0) -> None:
    if not re.search(pattern, text, flags):
        fail(message)


def forbid(pattern: str, message: str, flags: int = 0) -> None:
    if re.search(pattern, text, flags):
        fail(message)


def require_count(pattern: str, expected: int, message: str, flags: int = 0) -> None:
    actual = len(re.findall(pattern, text, flags))
    if actual != expected:
        fail(f"{message} (expected {expected}, got {actual})")


MODULE_MARKERS = (
    "MODULE: platform and filesystem helpers",
    "MODULE: download and supply-chain helpers",
    "MODULE: config persistence",
    "MODULE: subscription generation and serving",
    "MODULE: user quota state",
    "MODULE: service lifecycle",
    "MODULE: install and update",
    "MODULE: relay routing",
    "MODULE: WARP routing",
    "MODULE: menus and entrypoint",
)

for marker in MODULE_MARKERS:
    require(re.escape(marker), f"single-file script must keep a clear {marker} section")

forbid(
    r"^\s*(source|\.)\s+[^\n]*(argov|lib|modules)",
    "installed-user compatibility requires argov.sh to remain self-contained and not source split-out module files yet",
    flags=re.MULTILINE,
)
require(
    r"install_ag_wrapper\(\)[\s\S]*cat > \"\$SCRIPT_PATH\"[\s\S]*bash -n \"\$T\"[\s\S]*chmod \+x \"\$SCRIPT_PATH\"",
    "the /usr/bin/ag wrapper must be generated by one central helper with syntax-checked self-update downloads",
)
wrapper_body = re.search(
    r"install_ag_wrapper\(\) \{(?P<body>[\s\S]*?)^\}",
    text,
    flags=re.MULTILINE,
)
if not wrapper_body:
    fail("install_ag_wrapper must be defined")
outside_wrapper = text[: wrapper_body.start()] + text[wrapper_body.end() :]
if re.search(r"cat > \"\$SCRIPT_PATH\"", outside_wrapper):
    fail("SCRIPT_PATH wrapper creation must stay centralized in install_ag_wrapper")
require(
    r"do_install\(\)[\s\S]*install_ag_wrapper[\s\S]*save_conf",
    "fresh install must keep installing /usr/bin/ag through the central wrapper helper",
)
require(
    r"migrate_argox_to_argov\(\)[\s\S]*install_ag_wrapper forward_args",
    "migration must keep installing /usr/bin/ag through the central wrapper helper while preserving argument forwarding",
)

require(
    r'\*\)\s+command systemctl "\$cmd" "\$@"',
    "non-Alpine systemctl wrapper must call command systemctl to avoid recursion",
)
require(r"save_var\(\)", "save_conf must use a shell-escaping save_var helper")
require(
    r"secure_work_dir_permissions\(\)",
    "script must have a central permission hardening helper for /etc/xray runtime files",
)
require(
    r"begin_argov_lock\(\)[\s\S]*flock -x[\s\S]*end_argov_lock\(\)[\s\S]*flock -u",
    "script must provide a flock-based lock helper for state file updates",
)
require(
    r"download_file\(\)[\s\S]*curl -fsSL[\s\S]*--retry[\s\S]*-o \"\$tmp\"[\s\S]*\[ -s \"\$tmp\" \][\s\S]*mv -f \"\$tmp\" \"\$dest\"",
    "remote downloads must use a temp file, retrying curl, non-empty validation, and atomic replacement",
)
require(
    r"download_script_checked\(\)[\s\S]*download_file[\s\S]*bash -n \"\$dest\"",
    "downloaded shell scripts must pass bash -n before execution",
)
require(
    r"sha256_file\(\)[\s\S]*sha256sum[\s\S]*shasum -a 256[\s\S]*openssl dgst -sha256",
    "script must support SHA256 calculation through common Linux/OpenSSL tools",
)
require(
    r"verify_sha256_file\(\)[\s\S]*sha256_file[\s\S]*tr 'A-F' 'a-f'[\s\S]*\[ \"\$actual\" = \"\$expected\" \]",
    "pinned release hashes must be verified with normalized SHA256 comparison",
)
require(
    r"xray_release_base\(\)[\s\S]*XRAY_VERSION[\s\S]*releases/download/\$\{XRAY_VERSION\}[\s\S]*xray_download_url\(\)[\s\S]*Xray-linux-\$\{arch\}\.zip",
    "Xray downloads must support optional version pinning without changing the default latest behavior",
)
require(
    r"xray_checksum_url\(\)[\s\S]*Xray-linux-\$\{arch\}\.zip\.dgst",
    "Xray downloads must know the official per-asset checksum sidecar URL",
)
require(
    r"cloudflared_release_base\(\)[\s\S]*CLOUDFLARED_VERSION[\s\S]*releases/download/\$\{CLOUDFLARED_VERSION\}[\s\S]*cloudflared_download_url\(\)[\s\S]*cloudflared-linux-\$\{arch\}",
    "cloudflared downloads must support optional version pinning without changing the default latest behavior",
)
require(
    r"download_xray_zip_checked\(\)[\s\S]*download_file \"\$url\" \"\$dest\"[\s\S]*XRAY_SHA256[\s\S]*xray_checksum_url[\s\S]*extract_sha256_from_dgst[\s\S]*verify_sha256_file \"\$dest\"",
    "Xray downloads must verify pinned SHA256 or the official .dgst sidecar when available",
)
require(
    r"download_cloudflared_checked\(\)[\s\S]*download_file \"\$url\" \"\$dest\"[\s\S]*CLOUDFLARED_SHA256[\s\S]*verify_sha256_file \"\$dest\"",
    "cloudflared downloads must verify the optional pinned SHA256 when configured",
)
require(
    r"run_warp_menu\(\)[\s\S]*download_script_checked[\s\S]*bash \"\$script\" \"\$mode\"",
    "WARP helper scripts must be downloaded through checked script execution",
)
require(
    r"save_conf\(\)[\s\S]*begin_argov_lock[\s\S]*mv -f \"\$tmp\" \"\$USER_CONF\"[\s\S]*end_argov_lock",
    "save_conf must hold the global state lock while replacing argov.conf",
)
require(
    r"ensure_users_file\(\)[\s\S]*begin_argov_lock[\s\S]*os\.replace\(tmp, path\)[\s\S]*end_argov_lock",
    "ensure_users_file must hold the global state lock while normalizing argov_users.json",
)
require(
    r"sync_xray_users\(\)[\s\S]*begin_argov_lock[\s\S]*os\.replace\(tmp, cfg_path\)[\s\S]*end_argov_lock",
    "sync_xray_users must hold the global state lock while replacing config.json",
)
forbid(
    r"chmod\s+777\s+\"\$WORK_DIR\"",
    "/etc/xray must not be made world-writable because it contains configs, generated scripts, and secrets",
)
forbid(
    r"curl -sLfo",
    "downloads must go through download_file/download_script_checked instead of direct curl -sLfo",
)
forbid(
    r"wget .*--no-check-certificate",
    "WARP helper downloads must not disable certificate checks",
)
require(
    r"is_safe_conf_file\(\)[\s\S]*^load_conf\(\)[\s\S]*is_safe_conf_file \"\$USER_CONF\"[\s\S]*\. \"\$USER_CONF\"",
    "load_conf must validate argov.conf before sourcing it for backward compatibility",
    flags=re.MULTILINE,
)
require(
    r"save_conf\(\)[\s\S]*local tmp[\s\S]*mktemp[\s\S]*mv -f \"\$tmp\" \"\$USER_CONF\"[\s\S]*secure_work_dir_permissions",
    "save_conf must write argov.conf atomically and restore secure permissions",
)
require_count(
    r"^manage_protocols\(\)",
    1,
    "manage_protocols must have exactly one active definition to avoid editing dead code",
    flags=re.MULTILINE,
)
require_count(
    r"^delete_protocol\(\)",
    1,
    "delete_protocol must have exactly one active definition to avoid editing dead code",
    flags=re.MULTILINE,
)
require(
    r"save_var NODE_NAME \"\$NODE_NAME\"",
    "NODE_NAME must be persisted through save_var so quotes cannot break argov.conf",
)
for var in ("XRAY_VERSION", "XRAY_SHA256", "CLOUDFLARED_VERSION", "CLOUDFLARED_SHA256"):
    require(
        rf"{var}=\"\$\{{{var}:-",
        f"{var} must have a backward-compatible default in load_conf",
    )
    require(
        rf"save_var {var} \"\${var}\"",
        f"{var} must be persisted through save_var",
    )
    require(
        rf"is_safe_conf_file\(\)[\s\S]*{var}",
        f"{var} must be accepted by the safe config whitelist",
    )
require(
    r"do_install\(\)[\s\S]*download_xray_zip_checked \"\$ARCH_ARG\" \"\$\{WORK_DIR\}/xray\.zip\"[\s\S]*download_cloudflared_checked \"\$CF_ARCH\" \"\$\{WORK_DIR\}/argo\"",
    "initial install must use checked Xray/cloudflared download helpers",
)
require(
    r"update_xray_core\(\)[\s\S]*download_xray_zip_checked \"\$ARCH_ARG\" \"\$utmp\"",
    "Xray update must use checked Xray download helper",
)
require(
    r"get_cdn\(\)[\s\S]*\[\s+-n \"\$v\"\s+\].*\[\s+\"\$v\"\s+!= \"null\"\s+\]",
    "get_cdn must fall back when current_cdn is empty or null",
)
require(
    r"interactive_install\(\)[\s\S]*select_protocols[\s\S]*do_install",
    "interactive install must call select_protocols before do_install",
)
forbid(
    r'echo "https://\$\{SUB_DOMAIN\}:\$\{SUB_PORT\}/sub\?token=\$\{SUB_TOKEN\}#\$\{NODE_NAME\}"',
    "subscription URLs must not append raw NODE_NAME fragments because strict clients can reject non-ASCII or spaces before sending the request",
)
forbid(
    r'echo "http://\$\{1:-127\.0\.0\.1\}:\$\{SUB_PORT\}\$\{SUB_PATH\}#\$\{NODE_NAME\}"',
    "HTTP subscription URLs must not append raw NODE_NAME fragments because strict clients can reject non-ASCII or spaces before sending the request",
)
require(
    r"json\.dumps\(v,\s*ensure_ascii=False\)",
    "Clash YAML strings must preserve UTF-8 instead of emitting surrogate escapes such as \\ud83d\\ude80",
)
require(
    r"json\.dumps\(i,\s*ensure_ascii=False\)",
    "Clash YAML list strings must preserve UTF-8 instead of emitting surrogate escapes such as \\ud83d\\ude80",
)
forbid(
    r'Content-Disposition\',f\'inline; filename="\{safe_name\}\.yaml"',
    "Clash subscription profile names must not include a forced .yaml suffix",
)
require(
    r"safe_name = up\.quote\('\$\{NODE_NAME\}',\s*safe=''\)",
    "subscription profile names must percent-encode all unsafe filename characters",
)
require(
    r"Content-Disposition',f\"inline; filename\*=UTF-8''\{safe_name\}\"",
    "subscription responses must expose NODE_NAME through UTF-8 filename metadata",
)
require(
    r'"bind-address": "\*"',
    "Clash profile should expose bind-address like common airport templates",
)
require(
    r'"external-controller": "127\.0\.0\.1:9090"',
    "Clash profile should include a local external-controller for dashboard clients",
)
require(
    r'"default-nameserver": \["223\.5\.5\.5", "119\.29\.29\.29"\]',
    "Clash DNS should include bootstrap default-nameserver entries",
)
require(
    r'"use-hosts": True',
    "Clash DNS should honor hosts entries",
)
require(
    r'"fallback-filter": \{[\s\S]*"geoip-code": "CN"',
    "Clash DNS should explicitly configure fallback-filter geoip-code CN",
)
require(
    r'"name": "Proxy", "type": "select"',
    "Clash profile should include an airport-style Proxy group",
)
require(
    r'"name": "Fallback", "type": "fallback"',
    "Clash profile should include an airport-style Fallback group",
)
require(
    r'"name": "AIChat", "type": "select"',
    "Clash profile should include an AIChat group",
)
require(
    r'"MATCH,Final"',
    "Clash profile should route unmatched traffic through Final",
)
require(
    r'"encryption": "none"',
    "Generated VLESS proxies should include encryption none for Mihomo compatibility",
)
require(
    r'p\["flow"\] = qs\.get\("flow", \[""\]\)\[0\]',
    "VLESS Reality/Vision conversion should preserve flow",
)
require(
    r'elif l\.startswith\("hysteria2://"\):',
    "Custom hysteria2 links should be converted into Clash YAML",
)
require(
    r'"type": "hysteria2"',
    "Custom hysteria2 links should produce Mihomo hysteria2 proxies",
)
require(
    r'ARGOV_USERS_FILE="/etc/xray/argov_users\.json"',
    "multi-user quota state must be persisted in /etc/xray/argov_users.json",
)
require(
    r"ensure_users_file\(\)",
    "script must migrate/create the ArgoV users database",
)
require(
    r"manage_users\(\)",
    "main menu must expose user quota management",
)
require(
    r"sync_xray_users\(\)",
    "user changes must sync enabled users into Xray clients without reinstalling",
)
require(
    r"start_stats_service\(\)",
    "script must install a traffic quota watcher service",
)
require(
    r"argov-stats\.service",
    "systemd installs must include an argov-stats traffic watcher",
)
require(
    r'"api":\{"tag":"api","services":\["StatsService"\]\}',
    "Xray config must enable StatsService API",
)
require(
    r'"stats":\{\}',
    "Xray config must enable stats collection",
)
require(
    r'"statsUserUplink":true',
    "Xray policy must enable per-user uplink stats",
)
require(
    r'"statsUserDownlink":true',
    "Xray policy must enable per-user downlink stats",
)
require(
    r'"email":"argov-',
    "Xray clients must include stable email values for per-user stats",
)
require(
    r'USER_TOKEN="\$\{1:-\}"[\s\S]*USER_JSON=',
    "subscription generator must accept a per-user token and resolve user JSON",
)
require(
    r'INCLUDE_CUSTOM=0[\s\S]*if \[ "\$IS_DEFAULT_USER" = "1" \]; then[\s\S]*INCLUDE_CUSTOM=1',
    "only the default/global subscription may include external custom links",
)
require(
    r'quota_bytes[\s\S]*used_up[\s\S]*used_down[\s\S]*enabled',
    "user records must track quota, bidirectional usage, and enabled state",
)
require(
    r'xray api statsquery[\s\S]*traffic>>>uplink[\s\S]*traffic>>>downlink',
    "traffic watcher must query Xray per-user uplink and downlink counters",
)
require(
    r"ENABLE_REALITY[\s\S]*gen_reality_shortid",
    "Reality install path must generate REALITY_SHORTID",
)
require(
    r'"shortIds":\["\'"\$\{REALITY_SHORTID\}"\'"\]',
    "initial Reality inbound must write REALITY_SHORTID into shortIds",
)
require(
    r'"fingerprint":"chrome"',
    "initial Reality inbound must include a Reality fingerprint",
)
require(
    r'HY2_PORT="\$\{HY2_PORT:-0\}"',
    "Hysteria2 must have a persisted editable port",
)
require(
    r'HY2_MPORT="\$\{HY2_MPORT:-\}"',
    "Hysteria2 port hopping range must be persisted separately from the listening port",
)
require(
    r"port_in_use_udp\(\)[\s\S]*proc/net/udp",
    "port_in_use_udp must check UDP via /proc/net/udp (zero-process, memory-safe)",
)
require(
    r"port_in_use_any\(\)[\s\S]*port_in_use_tcp \"\$1\"[\s\S]*port_in_use_udp \"\$1\"",
    "public UDP protocols must reject ports occupied by either TCP or UDP listeners",
)
require(
    r"is_port_range\(\)[\s\S]*BASH_REMATCH",
    "Hysteria2 mport input must validate numeric port ranges before writing links or firewall rules",
)
require(
    r'ENABLE_HY2=0',
    "Hysteria2 must be selectable as a built-in optional protocol",
)
require(
    r'gen_hy2_link\(\)',
    "built-in Hysteria2 must generate hysteria2:// subscription links",
)
require(
    r'elif tag == "hy2":[\s\S]*settings\["users"\] = users[\s\S]*settings\["clients"\] = users',
    "Hysteria2 user sync must write both users and clients for Xray version compatibility",
)
require(
    r'build_hy2_inbound\(\)[\s\S]*"protocol":"hysteria","tag":"hy2"[\s\S]*"settings":\{"version":2,"users":\[\{"auth":"\'"\$\{auth\}"\'","level":0,"email":"\'"\$\{email\}"\'"\}\],"clients":\[\{"auth":"\'"\$\{auth\}"\'","level":0,"email":"\'"\$\{email\}"\'"\}\]\}',
    "initial Hysteria2 inbound must write users and clients with per-user auth",
)
require(
    r'build_hy2_inbound\(\)[\s\S]*"streamSettings":\{"network":"hysteria","security":"tls"[\s\S]*"hysteriaSettings":\{"version":2',
    "initial Hysteria2 inbound must use the official hysteria transport with TLS",
)
require(
    r'build_hy2_inbound\(\)[\s\S]*"udpIdleTimeout":60',
    "Xray Hysteria2 udpIdleTimeout must be numeric seconds, not a string duration",
)
forbid(
    r'"udpIdleTimeout":"60s"',
    "Xray 26.3.27 rejects string udpIdleTimeout values for Hysteria2",
)
require(
    r'"tlsSettings":\{"alpn":\["h3"\]',
    "built-in Hysteria2 must expose h3 ALPN for clients",
)
require(
    r'tag=="hy2"',
    "Hysteria2 must be managed by tag hy2",
)
require(
    r'hysteria2://\$\{uuid\}@\$\{ip\}:\$\{hport\}\?sni=\$\{hsni\}&insecure=1&alpn=h3\$\{hmport_qs\}\$\{hy2_pin\}',
    "subscription generator must include built-in Hysteria2 links with self-signed TLS compatibility for local controllable users",
)
require(
    r'local qs="sni=\$4&insecure=1&alpn=h3"',
    "Hysteria2 share link helper must include both insecure and allowInsecure for self-signed certificates",
)
require(
    r'gen_hy2_link\(\)[\s\S]*local mport="\$6"[\s\S]*\[ -n "\$mport" \] && qs="\$\{qs\}&mport=\$\{mport\}"',
    "Hysteria2 share link helper must append mport only when port hopping is enabled",
)
require(
    r'links\+="hysteria2://\$\{uuid\}@\$\{ip\}:\$\{hport\}\?sni=\$\{hsni\}&insecure=1&alpn=h3',
    "subscription generator must include built-in Hysteria2 mport when port hopping is enabled",
)
require(
    r'mport = qs\.get\("mport", qs\.get\("ports", \[""\]\)\)\[0\][\s\S]*p\["ports"\] = mport[\s\S]*p\["hop-interval"\] = 30',
    "Clash YAML conversion must preserve Hysteria2 port hopping as ports and hop-interval",
)
require(
    r'build_hy2_inbound\(\)[\s\S]*udpHop',
    "Hysteria2 inbound builder must include udpHop for port hopping support",
)
require(
    r'build_hy2_inbound\(\)[\s\S]*"sniffing":\{"enabled":true,"destOverride":\["http","tls","quic"\],"routeOnly":true\}',
    "Hysteria2 inbound must enable route-only sniffing so server-side domain split rules can match QUIC/TLS destinations",
)
require(
    r'build_xray_config\(\)[\s\S]*"tag":"argo-in"[\s\S]*"sniffing":\{"enabled":true,"destOverride":\["http","tls","quic"\],"routeOnly":true\}[\s\S]*"tag":"vless-ws"[\s\S]*"sniffing":\{"enabled":true,"destOverride":\["http","tls","quic"\],"routeOnly":true\}[\s\S]*"tag":"vmess-ws"[\s\S]*"sniffing":\{"enabled":true,"destOverride":\["http","tls","quic"\],"routeOnly":true\}',
    "Argo/VLESS WS/VMess WS inbounds must enable route-only sniffing for relay domain split rules",
)
require(
    r'ROUTE_SNIFF_TAGS = \{"argo-in", "vless-ws", "vmess-ws", "reality", "hy2", "ss"\}[\s\S]*inbound\["sniffing"\] = dict\(ROUTE_SNIFFING\)',
    "existing proxy inbounds must be patched with route-only sniffing during user sync and relay apply",
)
require(
    r'relay_apply\(\)[\s\S]*def enable_route_sniffing\(config\):[\s\S]*with open\(CONFIG, \'r\'\) as f:[\s\S]*config = json\.load\(f\)[\s\S]*enable_route_sniffing\(config\)',
    "relay apply must patch old configs with route-only sniffing before injecting relay routing rules",
)
require(
    r'relay_apply\(\)[\s\S]*DOMAIN_PREFIXES = \("domain:", "full:", "regexp:", "keyword:", "geosite:", "ext:", "dotless:"\)[\s\S]*def normalize_relay_domains\(items\):[\s\S]*d = "domain:" \+ d\.lstrip\("\."\)[\s\S]*relay_domains = normalize_relay_domains\(DOMAINS\)[\s\S]*relay_rule = \{"type": "field", "domain": relay_domains, "outboundTag": "relay-out"\}',
    "relay split domains must be normalized to Xray domain matchers so bare domains, wildcards, and URLs route through relay-out reliably",
)
require(
    r'RELAY_LINK_ENV="\$RELAY_LINK" RELAY_MODE_ENV="\$RELAY_MODE" python3',
    "relay links must be passed to Python through environment variables so quotes in share links cannot break the script",
)
require(
    r"def split_host_port\(server, default_port=443\):[\s\S]*server\.startswith\('\['\)[\s\S]*server\.count\(':'\) > 1",
    "relay parser must support bracketed IPv6 endpoints without corrupting host:port parsing",
)
require(
    r"def apply_stream\(out, network='tcp', security='none', sni='', qs=None\):[\s\S]*\"realitySettings\"[\s\S]*\"tlsSettings\"[\s\S]*\"wsSettings\"",
    "relay parser must preserve VLESS/VMess/Trojan transport settings such as WS, TLS, and Reality",
)
require(
    r'network = qs\.get\(\'type\', qs\.get\(\'network\', \[\'tcp\'\]\)\)\[0\][\s\S]*apply_stream\(out, network, security, sni, qs\)',
    "relay VLESS outbound must honor type/network and stream security parameters instead of assuming plain tcp or ws",
)
forbid(
    r"re\.search\(r'vless://\(\[\^@\]\+\)@\(\[\^:\]\+\):\(\\d\+\)",
    "relay VLESS parser must not use host regexes that reject IPv6 endpoints",
)
forbid(
    r"re\.search\(r'trojan://\(\[\^@\]\+\)@\(\[\^:\]\+\):\(\\d\+\)",
    "relay Trojan parser must not use host regexes that reject IPv6 endpoints",
)
require(
    r"apply_hy2_hop_rules\(\)[\s\S]*dport=\"\$\{mport//-/:\}\"[\s\S]*-p udp --dport \"\\\$dport\"[\s\S]*--to-ports \"\\\$listen_port\"",
    "Hysteria2 port hopping must install UDP REDIRECT rules to the single Xray listening port with iptables range syntax",
)
require(
    r"disable_hy2_hop_rules\(\)[\s\S]*argov-hy2-hop[\s\S]*iptables[\s\S]*-D PREROUTING",
    "Hysteria2 port hopping must have cleanup for persisted service and iptables rules",
)
require(
    r"clear_hy2_mport_config\(\)[\s\S]*HY2_MPORT=\"\"[\s\S]*del\(\.finalmask\.quicParams\.udpHop\)",
    "Hysteria2 mport must be removed from config if firewall rule installation fails",
)
require(
    r'select\(\.tag=="reality" or \.tag=="ss" or \.tag=="hy2"\)',
    "reinstall keep-data path must preserve built-in Hysteria2 inbounds",
)
require(
    r"add_hy2_protocol\(\)",
    "Hysteria2 add flow must have a dedicated implementation instead of falling through unknown protocol handling",
)
require(
    r'a2\)\s+\[ "\$has_hy2" = 0 \] && add_hy2_protocol',
    "manage node menu must call the built-in Hysteria2 add flow",
)
require(
    r'delete_protocol\(\)[\s\S]*tag=="hy2"[\s\S]*ENABLE_HY2=0',
    "delete flow must remove Hysteria2 inbounds and persist ENABLE_HY2=0",
)
require(
    r"json_array_from_file\(\)",
    "WARP domain lists must be converted with json_array_from_file",
)
forbid(
    r"DOMAINS = \[\$\{domains_list\}\]",
    "WARP apply must not splice raw domain text into Python code",
)
forbid(
    r'domain":\[\$\{all_domains\}\]',
    "WARP mode switch must not splice raw domain text into Python code",
)
require(
    r"warp_auto_install_socks \|\| return",
    "WARP routing must stop when SOCKS installation fails",
)
require(
    r"核心功能.*进阶路由.*状态运维",
    "main menu must have three clearly separated groups: nodes, services, maintenance",
    flags=re.DOTALL,
)
require(
    r"节点配置修改",
    "change_config menu must exist with a clear purpose label",
)

# ——— Sing-box 内核 ———
require(
    r"install_singbox\(\)",
    "install_singbox() must exist",
)
require(
    r"build_singbox_config\(\)",
    "build_singbox_config() must exist",
)
require(
    r"generate_singbox_cert\(\)",
    "generate_singbox_cert() must exist",
)
require(
    r"detect_sb_arch\(\)",
    "detect_sb_arch() must exist for sing-box architecture detection",
)
require(
    r"sb_menu\(\)",
    "sb_menu() must provide the Sing-box management panel",
)
require(
    r"manage_sb_protocols\(\)",
    "manage_sb_protocols() must exist for protocol add/edit/delete",
)
require(
    r"gen_sb_hy2_link\(\)",
    "gen_sb_hy2_link() must exist",
)
require(
    r"gen_sb_tuic_link\(\)",
    "gen_sb_tuic_link() must exist",
)
require(
    r"gen_sb_anytls_link\(\)",
    "gen_sb_anytls_link() must exist",
)
require(
    r"gen_sb_reality_link\(\)",
    "gen_sb_reality_link() must exist for Sing-box Reality",
)
require(
    r"gen_sb_ss_link\(\)",
    "gen_sb_ss_link() must exist for Sing-box Shadowsocks",
)
# Sing-box 必须使用自签证书 (不依赖 allowInsecure)
require(
    r"SB_CERT_FILE.*fullchain\.pem",
    "Sing-box must have certificate file path defined",
)
# Sing-box 系统服务
require(
    r'sing-box\.service|sing-box.*openrc',
    "Sing-box systemd or OpenRC service must be defined",
)

# ——— iptables 流量统计 ———
require(
    r"setup_traffic_counters\(\)",
    "setup_traffic_counters() must exist for iptables traffic counting",
)
require(
    r"collect_traffic\(\)",
    "collect_traffic() must exist for collecting iptables counters",
)
require(
    r"reset_traffic_counters\(\)",
    "reset_traffic_counters() must exist for monthly reset",
)
require(
    r'iptables.*argov-traffic-in',
    "iptables argov-traffic-in rules must be created",
)
require(
    r'iptables.*argov-traffic-out',
    "iptables argov-traffic-out rules must be created",
)

# ——— v2: Sing-box 每用户流量配额 ———
require(
    r"sb_sync_users\(\)",
    "sb_sync_users() must exist for per-user Sing-box port allocation",
)
require(
    r"sb_build_per_user_inbounds\(\)",
    "sb_build_per_user_inbounds() must exist for per-user inbound generation",
)
require(
    r"sb_collect_user_traffic\(\)",
    "sb_collect_user_traffic() must exist for per-user traffic collection",
)
require(
    r"start_sb_stats_service\(\)",
    "start_sb_stats_service() must exist for argov-sb-stats daemon",
)
require(
    r"stop_sb_stats_service\(\)",
    "stop_sb_stats_service() must exist for sb-stats cleanup",
)
# sub_gen.sh 必须有每用户 Sing-box 端口读取
require(
    r"sb_ports.*sb_creds",
    "sub_gen.sh must read per-user sb_ports and sb_creds for dedicated links",
    flags=re.DOTALL,
)
